#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    mkd="mkdir -pv" \
    yt="youtube-dl --add-metadata -i" \
    yta="yt -x -f bestaudio/best" \
    ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
    ls="ls -hNA --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
    ka="killall" \
    g="git" \
    trem="transmission-remote" \
    YT="youtube-viewer" \
    sdn="sudo shutdown -h now" \
    f="$FILE" \
    e="$EDITOR &" \
    v="$EDITOR &" \
    p="sudo pacman" \
    xi="sudo xbps-install" \
    xr="sudo xbps-remove -R" \
    xq="xbps-query" \
    z="zathura"

alias \
    magit="nvim -c MagitOnly" \
    ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
    weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \

# .net commands
alias \
    dr="dotnet run -p" \
    dwr="dotnet watch run -p" \
    dt="dotnet test -p" \
    dwt="dotnet watch test -p" \
    ds="dotnet script" \

# Bluetooth battery
alias \
    boltune="bluetooth_battery 20:03:06:10:76:D8" \
    mpow="bluetooth_battery 05:AC:00:07:1C:53"

# dotfiles
alias \
    config="/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME" \
    configp="config push origin main" \
    configc="config commit"
